In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

iris = load_iris()

X = iris.data
y = iris.target

scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [6]:
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
X_train[:5]

In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

rf_clf = RandomForestClassifier(random_state=42)
lr_clf = LogisticRegression(random_state=42)

rf_clf.fit(X_train, y_train)
lr_clf.fit(X_train, y_train)

rf_pred = rf_clf.predict(X_test)
lr_pred = lr_clf.predict(X_test)

rf_acc = accuracy_score(y_test, rf_pred)
lr_acc = accuracy_score(y_test, lr_pred)

print("Random Forest Accuracy: {:.2f}%".format(rf_acc*100))
print("Logistic Regression Accuracy: {:.2f}%".format(lr_acc*100))


Random Forest Accuracy: 100.00%
Logistic Regression Accuracy: 100.00%


In [7]:
import pandas as pd
import numpy as np

data = pd.DataFrame(iris.data, columns = iris.feature_names)

In [8]:
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [9]:
data['target'] = iris.target

In [12]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [13]:
data.to_csv('iris.csv')

In [14]:
ls

iris.csv  sample_data/


In [15]:
iris_df = pd.read_csv('iris.csv')

In [16]:
iris_df

Unnamed: 0  sepal length (cm)  sepal width (cm)  petal length (cm)  \
0             0                5.1               3.5                1.4   
1             1                4.9               3.0                1.4   
2             2                4.7               3.2                1.3   
3             3                4.6               3.1                1.5   
4             4                5.0               3.6                1.4   
..          ...                ...               ...                ...   
145         145                6.7               3.0                5.2   
146         146                6.3               2.5                5.0   
147         147                6.5               3.0                5.2   
148         148                6.2               3.4                5.4   
149         149                5.9               3.0                5.1   

     petal width (cm)  target  
0                 0.2       0  
1                 0.2       0  
2                 0.2       0  
3                 0.2       0  
4                 0.2       0  
..                ...     ...  
145               2.3       2  
146               1.9       2  
147               2.0       2  
148               2.3       2  
149               1.8       2  

[150 rows x 6 columns]

In [17]:
iris_df.to_excel('iris.xlsx', index = False)

In [19]:
iris_xl = pd.read_excel('iris.xlsx')

In [22]:
iris_xl.drop('Unnamed: 0', axis =1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [21]:
X_train[:5]

array([[-1.50652052,  1.24920112, -1.56757623, -1.3154443 ],
       [-0.17367395,  3.09077525, -1.2833891 , -1.05217993],
       [ 1.03800476,  0.09821729,  0.36489628,  0.26414192],
       [-1.26418478,  0.78880759, -1.22655167, -1.3154443 ],
       [-1.74885626,  0.32841405, -1.39706395, -1.3154443 ]])

In [24]:
iris = pd.read_csv('iris.csv')

# 품종 데이터 원핫인코딩 수행
species_dummies = pd.get_dummies(iris['target'], prefix='species')
iris = pd.concat([iris, species_dummies], axis=1)

In [25]:
species_dummies

species_0  species_1  species_2
0            1          0          0
1            1          0          0
2            1          0          0
3            1          0          0
4            1          0          0
..         ...        ...        ...
145          0          0          1
146          0          0          1
147          0          0          1
148          0          0          1
149          0          0          1

[150 rows x 3 columns]

In [26]:
iris

Unnamed: 0  sepal length (cm)  sepal width (cm)  petal length (cm)  \
0             0                5.1               3.5                1.4   
1             1                4.9               3.0                1.4   
2             2                4.7               3.2                1.3   
3             3                4.6               3.1                1.5   
4             4                5.0               3.6                1.4   
..          ...                ...               ...                ...   
145         145                6.7               3.0                5.2   
146         146                6.3               2.5                5.0   
147         147                6.5               3.0                5.2   
148         148                6.2               3.4                5.4   
149         149                5.9               3.0                5.1   

     petal width (cm)  target  species_0  species_1  species_2  
0                 0.2       0          1          0          0  
1                 0.2       0          1          0          0  
2                 0.2       0          1          0          0  
3                 0.2       0          1          0          0  
4                 0.2       0          1          0          0  
..                ...     ...        ...        ...        ...  
145               2.3       2          0          0          1  
146               1.9       2          0          0          1  
147               2.0       2          0          0          1  
148               2.3       2          0          0          1  
149               1.8       2          0          0          1  

[150 rows x 9 columns]